### PR TITLE
fix: application crashes unexpectedly after full reload of details page

### LINKED ISSUE #33: Application crashes unexpectedly after full reload of details page
**Steps to reproduce:**
1.  Go to the details page of the article and copy URL
2. Open a new browser tab or new browser window
3. Paste copied link
4. App crashes

**Reason and proposed solution:**
The reason is that data for details page is passed from the list page via location state so if there is no location history available application breaks. We could check that and if data is missing fetch it from external API.

### PR DESCRIPTION
**Pull request by mwojslaw**
close #33

### CODE REVIEW

File: src/app/services/articles/index.ts [hunk 1]
```diff
@@ -46,4 +45,26 @@ const getArticlesService = (
...
+  };
+
+  return ApiService.get(url, params)
+    .then((response: any) => {
+      const { data } = response;
+      return {
+        ...response,
+        data: {
+          status: data.status,
+          article: data.articles[0],
```
Comment (iiskaandar) [inline src/app/services/articles/index.ts]: Maybe you can use here array destructuring instead of articles[0]?
`const [item] = data.articles;`
For me, it will be much clear in code.
